#############################################################################
# Makefile for building: main_widget_calendar
# Generated by qmake (3.0) (Qt 5.6.2)
# Project:  main_widget_calendar.pro
# Template: app
# Command: C:\ProgramData\Anaconda3\Library\bin\qmake.exe -o Makefile main_widget_calendar.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:\ProgramData\Anaconda3\Library\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: main_widget_calendar.pro C:\ProgramData\Anaconda3\Library\mkspecs\win32-msvc2015\qmake.conf C:\ProgramData\Anaconda3\Library\mkspecs\features\spec_pre.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\common\angle.conf \
		C:\ProgramData\Anaconda3\Library\mkspecs\common\msvc-base.conf \
		C:\ProgramData\Anaconda3\Library\mkspecs\common\msvc-desktop.conf \
		C:\ProgramData\Anaconda3\Library\mkspecs\qconfig.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dcore.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dinput.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dquick.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dquick_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dquickinput.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dquickrender.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3drender.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3drender_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_axbase.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_axbase_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_axcontainer.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_axcontainer_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_axserver.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_axserver_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_clucene_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_concurrent.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_core.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_core_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_dbus.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_dbus_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_designer.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_designer_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_designercomponents_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_enginio.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_enginio_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_gui.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_gui_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_help.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_help_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_labscontrols_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_labstemplates_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_location.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_location_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_multimedia.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_network.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_network_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_nfc.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_opengl.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_platformsupport_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_positioning.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_printsupport.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_qml.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_qml_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_qmltest.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_quick.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_quick_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_script.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_script_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_scripttools.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_scripttools_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_sensors.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_serialbus.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_serialbus_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_serialport.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_sql.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_sql_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_svg.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_svg_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_testlib.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_uitools.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_webchannel.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_webkit.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_webkit_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_webkitwidgets.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_webkitwidgets_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_websockets.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_widgets.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_winextras.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_winextras_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_xml.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_xml_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\qt_functions.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\qt_config.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\win32\qt_config.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\win32-msvc2015\qmake.conf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\spec_post.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\exclusive_builds.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\default_pre.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\win32\default_pre.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\resolve_config.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\exclusive_builds_post.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\default_post.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\win32\rtti.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\precompile_header.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\warn_on.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\qt.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\resources.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\moc.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\win32\opengl.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\uic.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\file_copies.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\win32\windows.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\testcase_targets.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\exceptions.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\yacc.prf \
		C:\ProgramData\Anaconda3\Library\mkspecs\features\lex.prf \
		main_widget_calendar.pro \
		C:\ProgramData\Anaconda3\Library\lib\qtmain.prl \
		C:\ProgramData\Anaconda3\Library\lib\Qt5PrintSupport.prl \
		C:\ProgramData\Anaconda3\Library\lib\Qt5Widgets.prl \
		C:\ProgramData\Anaconda3\Library\lib\Qt5Gui.prl \
		C:\ProgramData\Anaconda3\Library\lib\Qt5Core.prl
	$(QMAKE) -o Makefile main_widget_calendar.pro
C:\ProgramData\Anaconda3\Library\mkspecs\features\spec_pre.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\common\angle.conf:
C:\ProgramData\Anaconda3\Library\mkspecs\common\msvc-base.conf:
C:\ProgramData\Anaconda3\Library\mkspecs\common\msvc-desktop.conf:
C:\ProgramData\Anaconda3\Library\mkspecs\qconfig.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dcore.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dinput.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dlogic.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dquick.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dquick_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dquickinput.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dquickinput_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dquickrender.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3dquickrender_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3drender.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_3drender_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_axbase.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_axbase_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_axcontainer.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_axserver.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_axserver_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_bluetooth.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_clucene_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_concurrent.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_core.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_core_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_dbus.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_dbus_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_designer.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_designer_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_enginio.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_enginio_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_gui.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_gui_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_help.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_help_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_labscontrols_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_labstemplates_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_location.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_location_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_multimedia.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_network.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_network_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_nfc.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_nfc_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_opengl.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_opengl_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_openglextensions.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_platformsupport_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_positioning.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_positioning_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_printsupport.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_qml.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_qml_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_qmltest.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_quick.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_quick_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_script.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_script_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_scripttools.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_scripttools_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_sensors.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_sensors_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_serialbus.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_serialbus_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_serialport.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_serialport_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_sql.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_sql_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_svg.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_svg_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_testlib.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_testlib_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_uiplugin.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_uitools.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_uitools_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_webchannel.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_webkit.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_webkit_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_webkitwidgets.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_websockets.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_websockets_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_widgets.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_widgets_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_winextras.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_winextras_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_xml.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_xml_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\ProgramData\Anaconda3\Library\mkspecs\features\qt_functions.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\qt_config.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\win32\qt_config.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\win32-msvc2015\qmake.conf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\spec_post.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\exclusive_builds.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\default_pre.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\win32\default_pre.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\resolve_config.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\exclusive_builds_post.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\default_post.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\win32\rtti.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\precompile_header.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\warn_on.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\qt.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\resources.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\moc.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\win32\opengl.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\uic.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\file_copies.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\win32\windows.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\testcase_targets.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\exceptions.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\yacc.prf:
C:\ProgramData\Anaconda3\Library\mkspecs\features\lex.prf:
main_widget_calendar.pro:
C:\ProgramData\Anaconda3\Library\lib\qtmain.prl:
C:\ProgramData\Anaconda3\Library\lib\Qt5PrintSupport.prl:
C:\ProgramData\Anaconda3\Library\lib\Qt5Widgets.prl:
C:\ProgramData\Anaconda3\Library\lib\Qt5Gui.prl:
C:\ProgramData\Anaconda3\Library\lib\Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile main_widget_calendar.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
	-$(DEL_FILE) main_widget_calendar.exp
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) main_widget_calendar.lib

release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
